---
title: "Homework 5"
author: "Fareha Sameen"
date: "10/26/2020"
output:
  pdf_document: default
  html_document: default
group: Neshma and Hertz
---

dat_use <- subset(acs2017_ny,use_varb)
use_varb <- (AGE >= 25) & (AGE <= 55) & (LABFORCE == 2) & (WKSWORK2 > 4) & (UHRSWORK >= 35) & (CITIZEN == 1) & (female == 1) & ((educ_college == 1) | (educ_advdeg == 1))
 
# I'm looking for women, who have at least one college degree and are citizens. 
```

```

dat_use <- subset(acs2017_ny,use_varb)
model_1 <- lm(INCWAGE ~ AGE + I(AGE^2) + I(AGE^3) + I(AGE^4) + I(AGE^5) + I(AGE^6) )
summary(model_1)

require(stargazer)
stargazer(model_1, type = "text")

=================================================
                         Dependent variable:     
                    -----------------------------
                               INCWAGE           
-------------------------------------------------
AGE                         15,311.430***        
                             (3,882.985)         
                                                 
I(AGE2)                      -767.580***         
                              (220.401)          
                                                 
I(AGE3)                       25.856***          
                               (6.259)           
                                                 
I(AGE4)                       -0.481***          
                               (0.094)           
                                                 
I(AGE5)                       0.004***           
                               (0.001)           
                                                 
I(AGE6)                      -0.00001***         
                              (0.00000)          
                                                 
Constant                   -131,968.200***       
                            (26,551.430)         
                                                 
-------------------------------------------------
Observations                   163,158           
R2                              0.090            
Adjusted R2                     0.090            
Residual Std. Error   63,110.280 (df = 163151)   
F Statistic         2,701.493*** (df = 6; 163151)
=================================================
Note:                 *p<0.1; **p<0.05; ***p<0.01

NNobs <- length(INCWAGE) 
set.seed(12345) 
graph_obs <- (runif(NNobs) < 0.1) 
dat_graph <-subset(dat_use,graph_obs)

plot(INCWAGE ~ jitter(AGE, factor = 2), pch = 16, col = rgb(0.5, 0.5, 0.5, alpha = 0.2), ylim = c(0,150000), data = dat_graph)
to_be_predicted0 <- data.frame(AGE = 20:65, female = 1, educ_college = 1, educ_advdeg = 1)
to_be_predicted0$yhat <- predict(model_1, newdata = to_be_predicted0)
lines(yhat ~ AGE, data = to_be_predicted0)

#Through this I'm trying to look at higher polynomials for age up to 6 in order to see if the higher polynomials are significant, furthermore, this should also show whether there is a pattern of predicted wage as a function of age. 
 
#The data shows that though the polynomials for age increase, The plot shows that there is no correlation between age and income. There is no linear regression, showing that wages increase for people until about 45 and then they stop increasing and the curve starts going downward indicating that after about 50 years of age, the wages decrease. 
```

```

dat_use <- subset(acs2017_ny, use_varb)
model_2 <- lm(INCWAGE ~ I(AGE^2) + female + CITIZEN)
summary(model_2)  

require(stargazer)
stargazer(model_2, type = "text")

=================================================
                         Dependent variable:     
                    -----------------------------
                               INCWAGE           
-------------------------------------------------
I(AGE2)                       -3.243***          
                               (0.082)           
                                                 
female                     -15,127.730***        
                              (324.525)          
                                                 
CITIZEN                       -250.704           
                              (158.118)          
                                                 
Constant                    50,671.860***        
                              (329.352)          
                                                 
-------------------------------------------------
Observations                   163,158           
R2                              0.024            
Adjusted R2                     0.024            
Residual Std. Error   65,384.140 (df = 163154)   
F Statistic         1,315.896*** (df = 3; 163154)
=================================================
Note:                 *p<0.1; **p<0.05; ***p<0.01

NNobs <- length(INCWAGE) 
set.seed(12345) 
graph_obs <- (runif(NNobs) < 0.1) 
dat_graph <-subset(dat_use,graph_obs)

plot(INCWAGE ~ jitter(AGE, factor = 2), pch = 16, col = rgb(0.5, 0.5, 0.5, alpha = 0.2), ylim = c(0,150000), data = dat_graph)
to_be_predicted1 <- data.frame(AGE = 20:65, female = 1, educ_college = 1, educ_advdeg = 1, CITIZEN = 1)
to_be_predicted1$yhat <- predict(model_2, newdata = to_be_predicted1)
lines(yhat ~ AGE, data = to_be_predicted1)

# This data shows that there's a negative correlation between age and icnome, however, in this we're looking at women with at least one degree who are citizens. This also has the polynomial for age. The result shows that as age increases, the wage degreases. 

```

```

dat_use <- subset(acs2017_ny, use_varb)
model_3 <- lm(INCWAGE ~ I(AGE^3) + female + CITIZEN)
summary(model_3)   

require(stargazer)
stargazer(model_3, type = "text")

=================================================
                         Dependent variable:     
                    -----------------------------
                               INCWAGE           
-------------------------------------------------
I(AGE3)                       -0.050***          
                               (0.001)           
                                                 
female                     -14,841.340***        
                              (323.309)          
                                                 
CITIZEN                      -368.051**          
                              (157.528)          
                                                 
Constant                    50,261.850***        
                              (290.798)          
                                                 
-------------------------------------------------
Observations                   163,158           
R2                              0.031            
Adjusted R2                     0.031            
Residual Std. Error   65,128.780 (df = 163154)   
F Statistic         1,753.535*** (df = 3; 163154)
=================================================
Note:                 *p<0.1; **p<0.05; ***p<0.01

NNobs <- length(INCWAGE) 
set.seed(12345) 
graph_obs <- (runif(NNobs) < 0.1) 
dat_graph <-subset(dat_use,graph_obs)

plot(INCWAGE ~ jitter(AGE, factor = 2), pch = 16, col = rgb(0.5, 0.5, 0.5, alpha = 0.2), ylim = c(0,150000), data = dat_graph)
to_be_predicted2 <- data.frame(AGE = 20:65, female = 1, educ_college = 1, educ_advdeg = 1, CITIZEN = 1)
to_be_predicted2$yhat <- predict(model_3, newdata = to_be_predicted2)
lines(yhat ~ AGE, data = to_be_predicted2)

# I repeated the code again but with the different polynomial for age to see if the polynomial makes a difference, however, the graph is the same for different polynomials. I repeated this for polynomials up to age^6, but concluded that it does not make a difference. This may be the reason why we don't think we use the ppolynomial terms of dummy variables.
```
```

dat_use <- subset(acs2017_ny, use_varb)
model_4 <- lm(INCWAGE ~ I(AGE^4) + female + CITIZEN)
summary(model_4) 

require(stargazer)
stargazer(model_4, type = "text")

=================================================
                         Dependent variable:     
                    -----------------------------
                               INCWAGE           
-------------------------------------------------
I(AGE4)                       -0.001***          
                              (0.00001)          
                                                 
female                     -14,676.620***        
                              (322.524)          
                                                 
CITIZEN                      -447.373***         
                              (157.152)          
                                                 
Constant                    49,271.470***        
                              (273.728)          
                                                 
-------------------------------------------------
Observations                   163,158           
R2                              0.036            
Adjusted R2                     0.036            
Residual Std. Error   64,964.200 (df = 163154)   
F Statistic         2,038.334*** (df = 3; 163154)
=================================================
Note:                 *p<0.1; **p<0.05; ***p<0.01

NNobs <- length(INCWAGE) 
set.seed(12345) 
graph_obs <- (runif(NNobs) < 0.1) 
dat_graph <-subset(dat_use,graph_obs)

plot(INCWAGE ~ jitter(AGE, factor = 2), pch = 16, col = rgb(0.5, 0.5, 0.5, alpha = 0.2), ylim = c(0,150000), data = dat_graph)
to_be_predicted3 <- data.frame(AGE = 20:65, female = 1, educ_college = 1, educ_advdeg = 1, CITIZEN = 1)
to_be_predicted3$yhat <- predict(model_4, newdata = to_be_predicted3)
lines(yhat ~ AGE, data = to_be_predicted3)
```
```

dat_use <- subset(acs2017_ny, use_varb)
model_5 <- lm(INCWAGE ~ I(AGE^5) + female + CITIZEN)
summary(model_5)  

require(stargazer)
stargazer(model_5, type = "text")

=================================================
                         Dependent variable:     
                    -----------------------------
                               INCWAGE           
-------------------------------------------------
I(AGE5)                      -0.00001***         
                              (0.00000)          
                                                 
female                     -14,613.210***        
                              (322.231)          
                                                 
CITIZEN                      -479.475***         
                              (157.011)          
                                                 
Constant                    48,137.560***        
                              (264.610)          
                                                 
-------------------------------------------------
Observations                   163,158           
R2                              0.038            
Adjusted R2                     0.038            
Residual Std. Error   64,902.080 (df = 163154)   
F Statistic         2,146.393*** (df = 3; 163154)
=================================================
Note:                 *p<0.1; **p<0.05; ***p<0.01

NNobs <- length(INCWAGE) 
set.seed(12345) 
graph_obs <- (runif(NNobs) < 0.1) 
dat_graph <-subset(dat_use,graph_obs)

plot(INCWAGE ~ jitter(AGE, factor = 2), pch = 16, col = rgb(0.5, 0.5, 0.5, alpha = 0.2), ylim = c(0,150000), data = dat_graph)
to_be_predicted4 <- data.frame(AGE = 20:65, female = 1, educ_college = 1, educ_advdeg = 1, CITIZEN = 1)
to_be_predicted4$yhat <- predict(model_5, newdata = to_be_predicted4)
lines(yhat ~ AGE, data = to_be_predicted4)
```
```

dat_use <- subset(acs2017_ny, use_varb)
model_6 <- lm(INCWAGE ~ I(AGE^6) + female + CITIZEN)
summary(model_6)   

require(stargazer)
stargazer(model_6, type = "text")

=================================================
                         Dependent variable:     
                    -----------------------------
                               INCWAGE           
-------------------------------------------------
I(AGE6)                      -0.00000***         
                               (0.000)           
                                                 
female                     -14,619.220***        
                              (322.292)          
                                                 
CITIZEN                      -478.754***         
                              (157.040)          
                                                 
Constant                    47,076.310***        
                              (259.321)          
                                                 
-------------------------------------------------
Observations                   163,158           
R2                              0.038            
Adjusted R2                     0.038            
Residual Std. Error   64,913.750 (df = 163154)   
F Statistic         2,126.081*** (df = 3; 163154)
=================================================
Note:                 *p<0.1; **p<0.05; ***p<0.01

NNobs <- length(INCWAGE) 
set.seed(12345) 
graph_obs <- (runif(NNobs) < 0.1) 
dat_graph <-subset(dat_use,graph_obs)

plot(INCWAGE ~ jitter(AGE, factor = 2), pch = 16, col = rgb(0.5, 0.5, 0.5, alpha = 0.2), ylim = c(0,150000), data = dat_graph)
to_be_predicted5 <- data.frame(AGE = 20:65, female = 1, educ_college = 1, educ_advdeg = 1, CITIZEN = 1)
to_be_predicted5$yhat <- predict(model_6, newdata = to_be_predicted5)
lines(yhat ~ AGE, data = to_be_predicted5)
```
